// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductMicroService.DBContexts;

namespace ProductMicroService.Migrations
{
    [DbContext(typeof(ProductContext))]
    partial class ProductContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProductMicroService.Model.BuyerBid", b =>
                {
                    b.Property<int>("BuyerBidId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("BidEndDate");

                    b.Property<int>("BidPrice");

                    b.Property<string>("BuyerAddress");

                    b.Property<string>("BuyerCity");

                    b.Property<string>("BuyerEmail");

                    b.Property<string>("BuyerFirstName");

                    b.Property<string>("BuyerLastName");

                    b.Property<long>("BuyerPhone");

                    b.Property<int>("BuyerPin");

                    b.Property<string>("BuyerState");

                    b.Property<int>("ProductId");

                    b.HasKey("BuyerBidId");

                    b.ToTable("BuyerBids");
                });

            modelBuilder.Entity("ProductMicroService.Model.Category", b =>
                {
                    b.Property<int>("ProductCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ProductCategoryDescription");

                    b.Property<string>("ProductCategoryName");

                    b.HasKey("ProductCategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new { ProductCategoryId = 1, ProductCategoryDescription = "Painting", ProductCategoryName = "Painting" },
                        new { ProductCategoryId = 2, ProductCategoryDescription = "Sculptor", ProductCategoryName = "Sculptor" },
                        new { ProductCategoryId = 3, ProductCategoryDescription = "Ornament", ProductCategoryName = "Ornament" }
                    );
                });

            modelBuilder.Entity("ProductMicroService.Model.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("BidEndDate");

                    b.Property<int>("BidStartingPrice");

                    b.Property<int>("CategoryId");

                    b.Property<string>("ProductDetailedDescription");

                    b.Property<string>("ProductName");

                    b.Property<string>("ProductShortDescription");

                    b.Property<string>("SellerAddress");

                    b.Property<string>("SellerCity");

                    b.Property<string>("SellerEmail");

                    b.Property<string>("SellerFirstName");

                    b.Property<string>("SellerLastName");

                    b.Property<long>("SellerPhone");

                    b.Property<int>("SellerPin");

                    b.Property<string>("SellerState");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
